### ISSUE TITLE
[Bug] Raw Ore item tags do not seem to be registering properly.

### ISSUE THREAD

**Issue by ambientNexus** [DM-Earth/Conveniented-Forge-Tags#2]
![image](https://user-images.githubusercontent.com/53546918/228089250-07d9bc4a-cbb3-4fd9-8330-c76ceffea49c.png)
![image](https://user-images.githubusercontent.com/53546918/228089295-273e01d8-464f-456e-a2bd-fb2f62a540ff.png)
![image](https://user-images.githubusercontent.com/53546918/228089370-a955b579-c19a-4a9c-be83-b59087bcd4a9.png)
![image](https://user-images.githubusercontent.com/53546918/228089376-5c523ec1-9ae9-44dd-a307-011bf46788a0.png)
All Raw Ores that rely on this mod cannot be crushed with create or smelted with Hephaestus, while Raw Ore Blocks work properly.
![image](https://user-images.githubusercontent.com/53546918/228089609-7b3629a3-0157-467c-ab61-b4ae801eb5a8.png)

**Comment by JieningYu** [comment]
this seems is a REI displaying issue

**Comment by ambientNexus** [comment]
> this seems is a REI displaying issue

Nope, the actual recipes don't work. Probably should've included the screenshots of that in the initial post.
![image](https://user-images.githubusercontent.com/53546918/228126113-18bbc117-d077-4537-abad-58c5fb019985.png)
![image](https://user-images.githubusercontent.com/53546918/228126118-f9f5953b-36dc-424f-a604-d1d9521596ba.png)

**Comment by ambientNexus** [comment]
And to confirm the issue isn't just with my modpack, the same issue appears in Cabricality.
![image](https://user-images.githubusercontent.com/53546918/228127005-79309bcc-a53a-4c93-a782-617ccaa09427.png)
![image](https://user-images.githubusercontent.com/53546918/228127007-16a804c0-b8a2-4ee7-94d6-e93d43550f20.png)
![image](https://user-images.githubusercontent.com/53546918/228127013-58789aca-3382-4112-8a2c-2986b3dd891a.png)
![image](https://user-images.githubusercontent.com/53546918/228127144-94c6dcc7-4031-4b00-9cb5-576d74f4295c.png)

**Comment by JieningYu** [comment]
Raw ores are not intended to be obtained

**Comment by newtrogicNexus** [comment]
I don't get how that changes the fact that this mod does not properly register their tags.
